### PR TITLE
Fixed rendering when both viewbox and width/height attributes are pre…

### PR DESCRIPTION
**Pull request by MichaelHeerklotz**
Fixed rendering when both viewbox and width/height attributes are present

### CODE REVIEW

**Comment by shakiba** [comment]
Thanks for the PR! :) Do you have a npmjs.com account to publish a new version?

**Comment by MichaelHeerklotz** [comment]
You are welcome :) Here is my npmjs account: https://www.npmjs.com/~michaelheerklotz (username michaelheerklotz). This would be great, I will switch back to the official package and unpublish my custom one.

**Comment by shakiba** [comment]
:+1: I added you to the project, let me know if you need anything else from me, thanks for your contribution!

**Comment by MichaelHeerklotz** [comment]
Thank you very much. The code seems pretty stable now, so I have released version 0.4.0 on npmjs and deprecated my fork package (unpublish did not work because more than 72hours have passed since the release).

**Comment by shakiba** [comment]
Amazing, finally an update after 4 years! 😅

**Pull request merged**
