### PR TITLE
Fix performance issues and code clean-up

### LINKED ISSUE #41: Performance for svg -> png has decreased between 0.2.8 and 0.3.2
The performance when converting svg files to png has decreased quite a bit between those versions. It's most likely related to the PhantomJS changes. It's not a bug in that sense and it's not critical. I just wanted to mention it, as the difference is pretty huge.

For a sample file, real processing time went from 0.7 seconds to 12.8 seconds. The generated files are the same.

### PR DESCRIPTION
**Pull request by mdeboer**
I found that using `phantomjs-prebuilt` caused a massive slowdown compared to when `phantomjs2` was used so I reverted back to `phantomjs2`. This should fix #41 👍 

Also cleaned up the code a bit and added eslint to keep it clean 😉  Works lovely again!

### CODE REVIEW

**Comment by mdeboer** [comment]
I noticed that I broke support for NodeJS 0.10 and lower, but is that really an issue? 😜

**Comment by mdeboer** [comment]
Can anyone have a look at this? The only reason the checks have failed is because of support for NodeJS 0.10 and lower (which imho is deprecated anyway).

**Comment by shakiba** [comment]
@mdeboer Thanks for your PR! Can you please share some examples which show the performance difference is significant? phantomjs2 is a fork of phantomjs-prebuilt, but phantomjs-prebuilt is more up to date.

Also I'm trying some alternatives to replace phantomjs in near future.

**Comment by mdeboer** [comment]
@shakiba Sure np, I'll get some numbers 👍

**Comment by JimmyCushnie** [comment]
Why was this closed?

**Comment by mdeboer** [comment]
> Why was this closed?

My bad really, didn't have the time to do testing. But if someone else does, feel free to do so and/or merge 👍

**Comment by shakiba** [comment]
phantomjs is not used anymore.

**Comment by mdeboer** [comment]
Then I'll close this, thanks! 👍

**Pull request closed without merging**
